### PR TITLE
feat: Move server-side stuff to peerDependencies

### PR DESCRIPTION
**Pull request by eordano**
This should greatly reduce the amount of dependencies we add to client-side apps using this package.

Also moves `validate-commit-msg` to devDependencies

### CODE REVIEW

**Comment by NicoSantangelo** [comment]
Now that pg is a peer-dep specs are failing (just tried to do an `npm run build`):
image

so shouldn't we fix the circle config before it fails too?

**Comment by NicoSantangelo** [comment]
Also merging this would mean that updating commons on projects that depend on any peer dependency will break on restart, so we have to do a good job of communicating it (the marketplace comes to mind)

**Comment by eordano** [comment]
@NicoSantangelo Added PR to marketplace, https://github.com/decentraland/marketplace/pull/168

**Comment by NicoSantangelo** [comment]
Cool! I'm testing a few things back there but i'll test and merge both asap

**Pull request merged**
